SELECT a, b, COUNT(*) FROM tokens GROUP BY a, b ORDER BY COUNT(*) DESC;

SELECT ARRAY_AGG(DISTINCT a), an, ARRAY_AGG(DISTINCT b), bn, COUNT(*)
    FROM tokens WHERE an != bn GROUP BY an, bn ORDER BY COUNT(*) DESC LIMIT 999;
